### ISSUE TITLE
es6

### ISSUE THREAD

**Issue by conorhastings** [socialtables/socialtables.github.io#10]
https://github.com/airbnb/javascript 

airbnb guide which our guide is based off of has updated to include es6 style. as we start to do more things with es6 and add people to the team we should reevaluate where we stand/update our guide.

**Comment by danmactough** [comment]
@conorhastings Why close this? Should we open a convo?

**Comment by conorhastings** [comment]
@danmactough the reason i closed it is just because of the age of the issue/lack of traction on the issue, as i start to look here to develop the github.io page this didn't seem to be the appropriate place for the issue, especially with the existence of https://github.com/socialtables/javascript which i recently discovered. Either way, yeah probably a convo is the best place for this in terms of visibility + belonging, will open tomorrow.

**Comment by danmactough** [comment]
> especially with the existence of https://github.com/socialtables/javascript which i recently discovered

o_0 ... I had no idea that existed...
