### ISSUE TITLE
CSS Style Guide Edits

### ISSUE THREAD

**Issue by pbmasigla** [socialtables/socialtables.github.io#7]
-get code boxes to work for examples (hard to read)
-"Put line breaks between rulesets" example is unclear
-the lower-case rule is mentioned in 2 sections, the Preprocessor Variable Naming and under Rules (maybe we should just keep it in its own section)
-In the "Property Order" section, in "Other Style Properties" it says "Order does not matter". Can you clarify that? A bit confusing. I would say it does.
-This guide also goes into ordering a little more -> http://mdo.github.io/code-guide/#css  
-Under "Variables" add a code section showing how to create it
-Good further readings
-http://mdo.github.io/code-guide/#css GREAT guide for other missed content or more examples. 
-http://caniuse.com/# browser support use

In general, the page is hard to read. Maybe instead of an html let it be a readme.md?

**Comment by pbmasigla** [comment]
@rovolution

**Comment by rovolution** [comment]
@pbmasigla apparently i had forgotten to update it to my latest version!

Everything should be up to date now. check it out again
